application: ascii
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers: 
- url: /static
  static_dir: xyz

- url: /.*
  script: ascii.app

libraries:
- name: jinja2
  version: latest